on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      action:
        required: true
        type: string
jobs:
  run_action:
    runs-on: ubuntu-latest
    steps:
      name: Checkout
      uses: actions/checout@v4
      name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{inputs.python-version}}
     
