on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      action:
        required: true
        type: string
jobs:
  run_action:
    runs-on: ubuntu-latest
    steps:
     
